FROM microsoft/aspnetcore:2.0
RUN apt-get update && apt-get -y install openssh-server unzip curl supervisor

RUN mkdir /var/run/sshd
RUN echo 'root:debug' | chpasswd
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

ARG source
WORKDIR /app
EXPOSE 80 22
COPY ${source:-obj/Docker/publish} .
#RUN ["chmod", "+x", "entrypoint.sh"]
ENTRYPOINT ["/usr/bin/supervisord"]